baseURL = "http://example.org/"
languageCode = "en-us"
title = "Writings"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "I'm Judson Stevens"
author = "Judson Stevens"
profilePicture = "images/Headshot.jpeg"
contentRatio = 0.65

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/judsonstevens/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/JudsonStevens"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@judsonstevens.dev"

[params.math]
enable = true
use = "katex"

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true