apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-site-ingress
  namespace: personal-site
spec:
  defaultBackend:
    service:
      name: personal-site-deployment
      port:
        number: 80
  rules:
    - host: judsonstevens.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-site-deployment
                port:
                  number: 80
